name: Deploy from Staging to Production

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'staging'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Latest Image Tag from GHCR
      id: get-latest-tag
      env:
        GH_TOKEN: ${{ secrets.MY_PAT_SECRET }}  # Use your PAT for authentication
      run: |
        latest_tag=$(gh api "/users/${{ github.repository_owner }}/packages/container/managefarmspro/versions?package_type=container" --jq '.[].metadata.container.tags[0]' | sort -r | head -n 1)
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV  # Set it as an environment variable
        echo "Latest Tag: $latest_tag"  # Debugging

    - name: Debug Latest Tag
      run: |

        echo "The latest tag fetched: ${{ env.latest_tag }}"  # Confirm the tag is set


    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USERNAME }}
        key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
        script: |
          latest_tag=${{ env.latest_tag }}
          echo "Deploying image with tag: $latest_tag"
          docker pull ghcr.io/${{ github.repository_owner }}/managefarmspro:$latest_tag
          export CUSTOM_IMAGE="ghcr.io/${{ github.repository_owner }}/managefarmspro"
          export CUSTOM_TAG="$latest_tag"
          cd /home/sihan/production/frappe_docker
          sed -i "s|ghcr.io/khalandarsihan/managefarmspro/frappe-app:.*|${CUSTOM_IMAGE}:${CUSTOM_TAG}|g" pwd.yml
          docker compose --env-file .env -f pwd.yml down
          docker system prune -af
          docker volume prune -f
          docker compose --env-file .env -f pwd.yml pull
          docker compose --env-file .env -f pwd.yml up -d

