name: CD

on:
  push:
    branches:
      - staging  # Trigger CD on staging pushes

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_PAT_SECRET }}

      - name: Generate Version Number
        run: |
          version=$(date +"%Y%m%d%H%M%S")
          echo "version=$version" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg FRAPPE_REPO=https://github.com/khalandarsihan/frappe.git \
            --build-arg FRAPPE_BRANCH=version-15 \
            --build-arg ERPNEXT_REPO=https://github.com/khalandarsihan/erpnext.git \
            --build-arg ERPNEXT_BRANCH=version-15 \
            --build-arg PAYMENTS_REPO=https://github.com/khalandarsihan/payments.git \
            --build-arg PAYMENTS_BRANCH=version-15 \
            --build-arg CUSTOM_APP_REPO=$GITHUB_WORKSPACE \
            -t ghcr.io/${{ github.repository_owner }}/managefarmspro:${{ env.version }} \
            -t ghcr.io/${{ github.repository_owner }}/managefarmspro:latest \
            --file Containerfile \
            --push .

      - name: Output Image and Tag
        run: |
          echo "Built and pushed Docker image: ghcr.io/${{ github.repository_owner }}/managefarmspro:${{ env.version }}"

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export CUSTOM_IMAGE="ghcr.io/${{ github.repository_owner }}/managefarmspro"
            export CUSTOM_TAG="${{ env.version }}"
            echo "Deploying Docker image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}"
            sed -i "s|ghcr.io/khalandarsihan/managefarmspro/frappe-app:.*|${CUSTOM_IMAGE}:${CUSTOM_TAG}|g" /home/sihan/staging/frappe_docker/pwd.yml
            cd /home/sihan/staging/frappe_docker
            docker compose -f pwd.yml down
            docker system prune -af    # Docker pruning after docker compose down
            docker volume prune -f     # Volume pruning after docker compose down
            docker compose -f pwd.yml pull
            docker compose -f pwd.yml up -d
            sleep 300
            if curl -s -o /dev/null -w "%{http_code}" https://khasihan.xyz | grep 200; then
              echo "Deployment successful!"
            else
              echo "Deployment failed"
              exit 1

