name: CD

on:
  push:
    branches:
      - staging
  workflow_dispatch: # This allows manual triggering from the GitHub UI

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Version Number
        run: |
          version=$(date +"%Y%m%d%H%M%S")
          echo "version=$version" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker build \
            --build-arg=APPS_JSON_BASE64=${{ secrets.APPS_JSON_BASE64 }} \
            --tag=ghcr.io/khalandarsihan/managefarmspro/frappe-app:${{ env.version }} \
            --file=/home/sihan/frappe_docker/images/custom/Containerfile .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/khalandarsihan/managefarmspro/frappe-app:${{ env.version }}

      - name: Make Docker Image Public and Attach to Repo
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/khalandarsihan/packages/container/managefarmspro/visibility \
            -d '{"visibility":"public"}'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and Deploy Frappe App
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/sihan/staging/frappe_docker
            docker compose -f compose.yaml down
            docker compose -f compose.yaml pull
            docker compose -f compose.yaml up -d
            sleep 300
            if curl -s -o /dev/null -w "%{http_code}" https://khasihan.xyz | grep 200; then
              echo "Deployment successful!"
            else
              echo "Deployment failed"
              exit 1
            fi

      - name: Finish CD
        if: success()
        run: echo "CD process completed."

