name: CD

on:
  push:
    branches:
      - staging
  workflow_dispatch: # This allows manual triggering from the GitHub UI

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Version Number
        run: |
          version=$(date +"%Y%m%d%H%M%S")
          echo "version=$version" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_PAT_SECRET }}

      - name: Build and Tag Docker Image
        run: |
          cd /home/sihan/frappe_docker
          docker build --pull \
            --build-arg=FRAPPE_PATH=https://github.com/khalandarsihan/erpnext \
            --build-arg=FRAPPE_BRANCH=version-15 \
            --build-arg=PYTHON_VERSION=3.11.9 \
            --build-arg=NODE_VERSION=18.20.2 \
            --build-arg=APPS_JSON_BASE64=${{ secrets.APPS_JSON_BASE64 }} \
            --tag=ghcr.io/khalandarsihan/managefarmspro/frappe-app:${{ env.version }} \
            --file=images/custom/Containerfile .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/khalandarsihan/managefarmspro/frappe-app:${{ env.version }}

      - name: Set Deployment Environment Variables
        run: |
          echo "CUSTOM_IMAGE=ghcr.io/khalandarsihan/managefarmspro/frappe-app" >> $GITHUB_ENV
          echo "CUSTOM_TAG=${{ env.version }}" >> $GITHUB_ENV

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and Deploy Frappe App
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export CUSTOM_IMAGE="${{ env.CUSTOM_IMAGE }}"
            export CUSTOM_TAG="${{ env.CUSTOM_TAG }}"
            echo "CUSTOM_IMAGE=${CUSTOM_IMAGE}"
            echo "CUSTOM_TAG=${CUSTOM_TAG}"
            sed -i "s|ghcr.io/khalandarsihan/managefarmspro/frappe-app:.*|${CUSTOM_IMAGE}:${CUSTOM_TAG}|g" /home/sihan/staging/frappe_docker/pwd.yml
            cd /home/sihan/staging/frappe_docker
            docker compose -f pwd.yml down
            docker system prune -af    # Docker pruning after docker compose down
            docker volume prune -f     # Volume pruning after docker compose down
            docker compose -f pwd.yml pull
            docker compose -f pwd.yml up -d
            sleep 300
            if curl -s -o /dev/null -w "%{http_code}" https://khasihan.xyz | grep 200; then
              echo "Deployment successful!"
            else
              echo "Deployment failed"
              exit 1
            fi

      - name: Clean up Docker components on Runner
        run: |
          docker system prune -af  # Pruning after all deployment steps are done
          docker volume prune -f

      - name: Finish CD
        if: success()
        run: echo "CD process completed."

