name: CD

on:
  push:
    branches:
      - staging
  workflow_dispatch: # This allows manual triggering from the GitHub UI

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and update Frappe app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd staging/frappe_docker/
            docker compose -f pwd.yml down
            sleep 120
            docker compose -f pwd.yml up -d
            sleep 120
            if curl -s -o /dev/null -w "%{http_code}" https://khasihan.xyz | grep 200; then
              echo "Deployment successful!"
            else
              echo "Deployment failed"
              exit 1
            fi
            exit

      - name: Finish CD
        if: success()
        run: echo "CD process completed."

