name: CD to Staging Server

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      CUSTOM_IMAGE: ghcr.io/${{ github.repository_owner }}/managefarmspro

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          echo "CUSTOM_TAG=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

      - name: SSH into Staging Server and Update Docker Compose
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export CUSTOM_IMAGE="${{ env.CUSTOM_IMAGE }}"
            export CUSTOM_TAG="${{ env.CUSTOM_TAG }}"
            echo "Updating Docker Compose configuration with new image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}"
            sed -i "s|ghcr.io/khalandarsihan/managefarmspro/frappe-app:.*|${CUSTOM_IMAGE}:${CUSTOM_TAG}|g" /home/sihan/staging/frappe_docker/pwd.yml
            cd /home/sihan/staging/frappe_docker

            # Stop and remove old containers
            echo "Stopping and removing existing containers..."
            docker compose -f pwd.yml down
            docker system prune -af
            docker volume prune -f

            # Pull the new image
            echo "Pulling the new image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}"
            docker compose -f pwd.yml pull

            # Start the updated containers
            echo "Starting the updated containers..."
            docker compose -f pwd.yml up -d

            # Verify deployment
            sleep 30
            if curl -s -o /dev/null -w "%{http_code}" https://khasihan.xyz | grep 200; then
              echo "Deployment successful!"
            else
              echo "Deployment failed"
              exit 1
            fi

      - name: Deployment Complete
        run: echo "CD Pipeline Completed Successfully"

