name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: main-managefarmspro-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Frappe Bench
        run: pip install frappe-bench

      - name: Initialize Bench with Forked Frappe
        run: |
          bench init --skip-redis-config-generation --skip-assets --python "$(which python)" --frappe-path https://github.com/khalandarsihan/frappe.git  --frappe-branch version-15 /home/runner/frappe-bench
        env:
          CI: 'Yes'

      - name: Install Forked Apps (ERPNext, Payments)
        working-directory: /home/runner/frappe-bench
        run: |
          bench get-app erpnext https://github.com/khalandarsihan/erpnext.git --branch version-15
          bench get-app payments https://github.com/khalandarsihan/payments.git --branch version-15
          bench get-app managefarmspro $GITHUB_WORKSPACE

      - name: Setup Frappe Site and Install Apps
        working-directory: /home/runner/frappe-bench
        run: |
          bench new-site --db-root-password root --admin-password admin development.localhost
          bench --site development.localhost install-app erpnext
          bench --site development.localhost install-app payments
          bench --site development.localhost install-app managefarmspro

      - name: Build Assets
        working-directory: /home/runner/frappe-bench
        run: bench build --site development.localhost

      - name: Run Tests for Custom App
        working-directory: /home/runner/frappe-bench
        run: bench run-tests --app managefarmspro

      - name: Clean Up Bench Environment
        working-directory: /home/runner/frappe-bench
        run: bench destroy-all

  handle_completion:
    runs-on: ubuntu-latest
    needs: [tests]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/staging' }}
    steps:
      - name: Complete CI Run
        run: echo "CI Pipeline Completed Successfully"

