name: Ngrok Setup

on: [pull_request]

jobs:
  ngrok_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install ngrok
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Simple HTTP Server
      run: |
        sudo apt install -y python3
        nohup python3 -m http.server 8000 &

    - name: Start Ngrok with Detailed Logging
      run: |
        ngrok http 8000 --region=us --log=stdout --log-level=debug --log-format=logfmt > ngrok.log &
        sleep 10  # wait for ngrok to initialize
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
        cat tunnels.json
        NGROK_URL=$(cat tunnels.json | jq -r .tunnels[0].public_url)
        echo "Ngrok URL: $NGROK_URL"
        echo $NGROK_URL > ngrok_url.txt

    - name: Check Ngrok URL
      run: |
        NGROK_URL=$(cat ngrok_url.txt)
        echo "Checking Ngrok URL: $NGROK_URL"
        curl -v $NGROK_URL

    - name: Expose Ngrok Dashboard
      run: |
        ngrok http 4040 --region=us --log=stdout --log-level=debug --log-format=logfmt > ngrok_dashboard.log &
        sleep 10  # wait for ngrok to initialize
        NGROK_DASHBOARD_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "Ngrok Dashboard URL: $NGROK_DASHBOARD_URL"
        echo $NGROK_DASHBOARD_URL > ngrok_dashboard_url.txt

    - name: Print Ngrok Logs
      run: |
        cat ngrok.log

    - name: Print Ngrok Dashboard URL
      run: |
        NGROK_DASHBOARD_URL=$(cat ngrok_dashboard_url.txt)
        echo "Ngrok Dashboard URL: $NGROK_DASHBOARD_URL"
